package io.github.eendroroy.fuelquota.mapper;

import io.github.eendroroy.fuelquota.dto.response.AuthResponse;
import io.github.eendroroy.fuelquota.entity.User;
import io.github.eendroroy.fuelquota.security.JwtTokenProvider;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * Assembles {@link AuthResponse} DTOs from a JWT token string and a {@link User} entity.
 *
 * <p>Delegates user-detail mapping to {@link UserMapper} so that the user
 * representation stays consistent across all response types.
 */
@Component
@RequiredArgsConstructor
public class AuthMapper {

    private final UserMapper userMapper;

    /**
     * Builds an {@link AuthResponse} containing the JWT access token and
     * a compact user representation.
     *
     * @param token JWT access token generated by {@link JwtTokenProvider}
     * @param user  the authenticated {@link User} entity
     * @return a populated {@link AuthResponse}
     */
    public AuthResponse toResponse(String token, User user) {
        return AuthResponse.builder()
                .token(token)
                .user(userMapper.toResponse(user))
                .build();
    }
}

